### ISSUE TITLE
Add checks on start date, end date years. 

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-creator#21]
1. Also have a better picker for start time end time. 
2. Have a picker for start/end dates too

**Comment by vsvishalsharma** [comment]
@suryabulusu, I'm eager to contribute to Avantifellows due to its mission and my TypeScript expertise. However, I'm facing challenges setting up the repository locally. Any guidance would be greatly appreciated. Thank you

![image](https://github.com/avantifellows/quiz-creator/assets/131687529/a60d3309-e9c3-454b-a8eb-a9de9254214a)

**Comment by Drish-xD** [comment]
Added ShadCn date-time picker for better UX/UI.
